#!/usr/bin/env python3
"""
GCode Generator — Plate Scanning Patterns
Supports: Serpentine (X/Y) and Diagonal Serpentine
Generates XY-only motion (no Z changes)
"""

from __future__ import annotations
import math
import sys
from pathlib import Path
from datetime import datetime


# ─────────────────────────────────────────────
#  Helpers
# ─────────────────────────────────────────────

def prompt_float(message: str, *, min_val: float = 0.0, allow_zero: bool = False) -> float:
    while True:
        raw = input(message).strip().replace(",", ".")
        try:
            value = float(raw)
            if (not allow_zero and value <= min_val) or (allow_zero and value < min_val):
                print(f"  ✗  Value must be > {min_val}. Try again.")
            else:
                return value
        except ValueError:
            print("  ✗  Please enter a valid number.")


def prompt_int(message: str, *, choices: list[int] | None = None) -> int:
    while True:
        raw = input(message).strip()
        try:
            value = int(raw)
            if choices and value not in choices:
                print(f"  ✗  Choose one of: {choices}")
            elif value < 1:
                print("  ✗  Value must be a positive integer.")
            else:
                return value
        except ValueError:
            print("  ✗  Please enter a whole number.")


def prompt_choice(message: str, valid: list[str]) -> str:
    valid_lower = [v.lower() for v in valid]
    while True:
        raw = input(message).strip().lower()
        if raw in valid_lower:
            return raw
        print(f"  ✗  Please enter one of: {' / '.join(valid)}")


def separator(char: str = "─", width: int = 60) -> None:
    print(char * width)


# ─────────────────────────────────────────────
#  GCode builders
# ─────────────────────────────────────────────

def header(feedrate: float, plate_x: float, plate_y: float, pattern: str) -> list[str]:
    now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    return [
        f"; ═══════════════════════════════════════════",
        f"; GCode generated by gcode_generator.py",
        f"; Date      : {now}",
        f"; Plate     : {plate_x} x {plate_y} mm",
        f"; Pattern   : {pattern}",
        f"; Feedrate  : {feedrate} mm/min",
        f"; ═══════════════════════════════════════════",
        "G90          ; Absolute positioning",
        "G21          ; Units in mm",
        f"F{feedrate:.1f}  ; Set feedrate",
        "G0 X0 Y0     ; Move to origin",
        "",
    ]


def footer() -> list[str]:
    return [
        "",
        "; ─── End of program ───",
        "G0 X0 Y0     ; Return to origin",
        "M30          ; Program end",
    ]


def build_serpentine_x(
    plate_x: float, plate_y: float,
    gap: float, n_lines: int,
    feedrate: float,
) -> list[str]:
    """
    Horizontal serpentine: lines run along X, stepping in Y.
    """
    lines: list[str] = header(feedrate, plate_x, plate_y, "Serpentine (X)")
    lines.append("; ─── Serpentine X-direction ───")

    for i in range(n_lines):
        y = round(i * gap, 6)
        if y > plate_y:
            break
        x_start, x_end = (0.0, plate_x) if i % 2 == 0 else (plate_x, 0.0)
        lines.append(f"G0 X{x_start:.4f} Y{y:.4f}  ; Line {i+1} start")
        lines.append(f"G1 X{x_end:.4f} Y{y:.4f}   ; Line {i+1} end")

    lines += footer()
    return lines


def build_serpentine_y(
    plate_x: float, plate_y: float,
    gap: float, n_lines: int,
    feedrate: float,
) -> list[str]:
    """
    Vertical serpentine: lines run along Y, stepping in X.
    """
    lines: list[str] = header(feedrate, plate_x, plate_y, "Serpentine (Y)")
    lines.append("; ─── Serpentine Y-direction ───")

    for i in range(n_lines):
        x = round(i * gap, 6)
        if x > plate_x:
            break
        y_start, y_end = (0.0, plate_y) if i % 2 == 0 else (plate_y, 0.0)
        lines.append(f"G0 X{x:.4f} Y{y_start:.4f}  ; Line {i+1} start")
        lines.append(f"G1 X{x:.4f} Y{y_end:.4f}   ; Line {i+1} end")

    lines += footer()
    return lines


def build_diagonal_serpentine(
    plate_x: float, plate_y: float,
    gap: float, n_lines: int,
    feedrate: float,
    angle_deg: float = 45.0,
) -> list[str]:
    """
    Diagonal serpentine at a given angle.
    Lines are parallel to the angle; the perpendicular offset = gap.
    """
    lines: list[str] = header(feedrate, plate_x, plate_y, f"Diagonal Serpentine ({angle_deg}°)")
    lines.append(f"; ─── Diagonal Serpentine at {angle_deg}° ───")

    angle_rad = math.radians(angle_deg)
    cos_a = math.cos(angle_rad)
    sin_a = math.sin(angle_rad)

    # Perpendicular direction (rotated 90°)
    perp_x = -sin_a
    perp_y = cos_a

    # For each line i, offset along perpendicular
    for i in range(n_lines):
        offset = i * gap
        # Midpoint along perpendicular
        mid_x = offset * perp_x
        mid_y = offset * perp_y

        # Extend line far enough to cover the plate diagonal
        half_len = math.hypot(plate_x, plate_y)

        raw_x1 = mid_x - half_len * cos_a
        raw_y1 = mid_y - half_len * sin_a
        raw_x2 = mid_x + half_len * cos_a
        raw_y2 = mid_y + half_len * sin_a

        # Clip to plate bounding box [0, plate_x] x [0, plate_y]
        pt1, pt2 = _clip_segment_to_rect(
            raw_x1, raw_y1, raw_x2, raw_y2,
            0, plate_x, 0, plate_y,
        )
        if pt1 is None:
            continue  # line misses plate

        x1, y1 = pt1
        x2, y2 = pt2

        # Serpentine: reverse direction on odd passes
        if i % 2 == 1:
            x1, y1, x2, y2 = x2, y2, x1, y1

        lines.append(f"G0 X{x1:.4f} Y{y1:.4f}  ; Line {i+1} start")
        lines.append(f"G1 X{x2:.4f} Y{y2:.4f}   ; Line {i+1} end")

    lines += footer()
    return lines


# ─────────────────────────────────────────────
#  Cohen-Sutherland line clipping (2D, AABB)
# ─────────────────────────────────────────────

_INSIDE = 0; _LEFT = 1; _RIGHT = 2; _BOTTOM = 4; _TOP = 8

def _region(x, y, xmin, xmax, ymin, ymax):
    code = _INSIDE
    if x < xmin: code |= _LEFT
    elif x > xmax: code |= _RIGHT
    if y < ymin: code |= _BOTTOM
    elif y > ymax: code |= _TOP
    return code

def _clip_segment_to_rect(x1, y1, x2, y2, xmin, xmax, ymin, ymax):
    c1 = _region(x1, y1, xmin, xmax, ymin, ymax)
    c2 = _region(x2, y2, xmin, xmax, ymin, ymax)
    while True:
        if not (c1 | c2):          # both inside
            return (x1, y1), (x2, y2)
        if c1 & c2:                # both outside same region
            return None, None
        c_out = c1 if c1 else c2
        if c_out & _TOP:
            x = x1 + (x2 - x1) * (ymax - y1) / (y2 - y1) if y2 != y1 else x1
            y = ymax
        elif c_out & _BOTTOM:
            x = x1 + (x2 - x1) * (ymin - y1) / (y2 - y1) if y2 != y1 else x1
            y = ymin
        elif c_out & _RIGHT:
            y = y1 + (y2 - y1) * (xmax - x1) / (x2 - x1) if x2 != x1 else y1
            x = xmax
        else:
            y = y1 + (y2 - y1) * (xmin - x1) / (x2 - x1) if x2 != x1 else y1
            x = xmin
        if c_out == c1:
            x1, y1, c1 = x, y, _region(x, y, xmin, xmax, ymin, ymax)
        else:
            x2, y2, c2 = x, y, _region(x, y, xmin, xmax, ymin, ymax)


# ─────────────────────────────────────────────
#  Main interactive flow
# ─────────────────────────────────────────────

def main() -> None:
    print()
    separator("═")
    print("  GCode Generator — Plate Scanning Patterns")
    separator("═")
    print()

    # ── Step 1: Plate size ──────────────────────
    print("[ Step 1 ]  Plate dimensions")
    plate_x = prompt_float("  Plate width  X (mm): ")
    plate_y = prompt_float("  Plate height Y (mm): ")
    print(f"  → Plate: {plate_x} x {plate_y} mm\n")

    # ── Step 2: Pattern ─────────────────────────
    separator()
    print("[ Step 2 ]  Travel pattern")
    print("  1  Serpentine X  (lines along X-axis, step in Y)")
    print("  2  Serpentine Y  (lines along Y-axis, step in X)")
    print("  3  Diagonal Serpentine")
    choice_pattern = prompt_choice("  Choose pattern [1/2/3]: ", ["1", "2", "3"])

    angle_deg = 45.0
    if choice_pattern == "3":
        angle_deg = prompt_float("  Diagonal angle in degrees (e.g. 45): ", allow_zero=True)

    pattern_names = {"1": "Serpentine X", "2": "Serpentine Y", "3": f"Diagonal Serpentine ({angle_deg}°)"}
    print(f"  → Pattern: {pattern_names[choice_pattern]}\n")

    # ── Step 3: Gap ─────────────────────────────
    separator()
    print("[ Step 3 ]  Line spacing")
    gap = prompt_float("  Gap between consecutive lines (mm): ")

    # Estimate how many lines fit
    if choice_pattern == "1":
        max_lines = int(plate_y / gap) + 1
        axis_label = "Y"
        axis_size = plate_y
    elif choice_pattern == "2":
        max_lines = int(plate_x / gap) + 1
        axis_label = "X"
        axis_size = plate_x
    else:
        # Diagonal: perpendicular distance across plate
        angle_rad = math.radians(angle_deg)
        perp_extent = abs(plate_x * math.sin(angle_rad)) + abs(plate_y * math.cos(angle_rad))
        max_lines = int(perp_extent / gap) + 1
        axis_label = "perpendicular"
        axis_size = round(perp_extent, 3)

    print(f"\n  ┌─ Estimated lines that fit ──────────────────┐")
    print(f"  │  Plate span along {axis_label}: {axis_size} mm")
    print(f"  │  Gap: {gap} mm  →  ≈ {max_lines} lines possible")
    print(f"  └──────────────────────────────────────────────┘\n")

    # ── Step 4: Number of lines ──────────────────
    separator()
    print("[ Step 4 ]  Number of lines")
    print(f"  Enter exact count  OR  press Enter to use all ({max_lines}).")
    raw_n = input(f"  Number of lines [default {max_lines}]: ").strip()
    if raw_n == "":
        n_lines = max_lines
    else:
        try:
            n_lines = int(raw_n)
            if n_lines < 1:
                raise ValueError
        except ValueError:
            print(f"  ✗  Invalid input — using estimated maximum: {max_lines}")
            n_lines = max_lines

    print(f"  → Lines to generate: {n_lines}\n")

    # ── Step 5: Feedrate ─────────────────────────
    separator()
    print("[ Step 5 ]  Feedrate")
    feedrate = prompt_float("  Feedrate (mm/min) [e.g. 1000]: ")
    print(f"  → Feedrate: {feedrate} mm/min\n")

    # ── Generate GCode ───────────────────────────
    separator("═")
    print("  Generating GCode …")

    if choice_pattern == "1":
        gcode_lines = build_serpentine_x(plate_x, plate_y, gap, n_lines, feedrate)
    elif choice_pattern == "2":
        gcode_lines = build_serpentine_y(plate_x, plate_y, gap, n_lines, feedrate)
    else:
        gcode_lines = build_diagonal_serpentine(plate_x, plate_y, gap, n_lines, feedrate, angle_deg)

    gcode_text = "\n".join(gcode_lines)

    
   1011
    # ── Save file ────────────────────────────────
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    pattern_slug = pattern_names[choice_pattern].replace(" ", "_").replace("(", "").replace(")", "").replace("°", "deg")
    filename = f"scan_{pattern_slug}_{timestamp}.gcode"

    # Find the repo folder, then create an 'output' path inside it
    repo_dir = Path(__file__).parent.resolve()
    output_dir = repo_dir / "output code"
    
    # This automatically creates the 'output' folder if it doesn't exist yet
    output_dir.mkdir(exist_ok=True)
    
    # Combine the output folder path with your filename
    out_path = output_dir / filename
    out_path.write_text(gcode_text, encoding="utf-8")

    # ── Summary ──────────────────────────────────
    move_count = sum(1 for l in gcode_lines if l.startswith("G0") or l.startswith("G1"))
    print(f"  ✓  {move_count} move commands written")
    print(f"  ✓  Saved to: {out_path.resolve()}")
    separator("═")

    # ── Preview (first 20 lines of GCode) ────────
    print("\n  ── GCode preview (first 20 motion lines) ──")
    motion = [l for l in gcode_lines if l.startswith("G")][:20]
    for line in motion:
        print(f"  {line}")
    if n_lines > 20:
        print(f"  … ({move_count - 20} more lines in file)")
    print()


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\n\n  Aborted.")
        sys.exit(0)


