; ═══════════════════════════════════════════
; GCode generated by gcode_generator.py
; Date      : 2026-05-26 10:25:18
; Plate     : 10.0 x 10.0 mm
; Pattern   : Serpentine (Y)
; Feedrate  : 10.0 mm/min
; ═══════════════════════════════════════════
G90          ; Absolute positioning
G21          ; Units in mm
F10.0  ; Set feedrate
G0 X0 Y0     ; Move to origin

; ─── Serpentine Y-direction ───
G0 X0.0000 Y0.0000  ; Line 1 start
G1 X0.0000 Y10.0000   ; Line 1 end
G0 X4.0000 Y10.0000  ; Line 2 start
G1 X4.0000 Y0.0000   ; Line 2 end

; ─── End of program ───
G0 X0 Y0     ; Return to origin
M30          ; Program end